//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicData
    {
        public BasicData()
        {
            this.BasicData1 = new HashSet<BasicData>();
            this.ProAdmissionDoneSteps = new HashSet<ProAdmissionDoneStep>();
            this.TblTherosholds = new HashSet<Theroshold>();
            this.TblTherosholds1 = new HashSet<Theroshold>();
            this.LabDiseaseAssignments = new HashSet<LabDiseaseAssignment>();
            this.ThresholdWarningStatus = new HashSet<ThresholdWarningStatu>();
        }
    
        public long Id { get; set; }
        public long BasicDataTypeId { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string Value1 { get; set; }
        public string Value2 { get; set; }
        public string Value3 { get; set; }
        public Nullable<decimal> NumericValue1 { get; set; }
        public Nullable<decimal> NumericValue2 { get; set; }
        public Nullable<decimal> NumericValue3 { get; set; }
        public Nullable<long> Code { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<BasicData> BasicData1 { get; set; }
        public virtual BasicData BasicData2 { get; set; }
        public virtual BasicDataType BasicDataType { get; set; }
        public virtual ICollection<ProAdmissionDoneStep> ProAdmissionDoneSteps { get; set; }
        public virtual ICollection<Theroshold> TblTherosholds { get; set; }
        public virtual ICollection<Theroshold> TblTherosholds1 { get; set; }
        public virtual ICollection<LabDiseaseAssignment> LabDiseaseAssignments { get; set; }
        public virtual ICollection<ThresholdWarningStatu> ThresholdWarningStatus { get; set; }
    }
}
