//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicDataType
    {
        public BasicDataType()
        {
            this.BasicData = new HashSet<BasicData>();
            this.BasicDataType1 = new HashSet<BasicDataType>();
            this.LabBasicDatas = new HashSet<LabBasicData>();
            this.LabDiseasesCharacters = new HashSet<LabDiseasesCharacter>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public Nullable<long> ParentId { get; set; }
        public Nullable<long> Code { get; set; }
    
        public virtual ICollection<BasicData> BasicData { get; set; }
        public virtual ICollection<BasicDataType> BasicDataType1 { get; set; }
        public virtual BasicDataType BasicDataType2 { get; set; }
        public virtual ICollection<LabBasicData> LabBasicDatas { get; set; }
        public virtual ICollection<LabDiseasesCharacter> LabDiseasesCharacters { get; set; }
    }
}
