//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complication
    {
        public long ComplicationID { get; set; }
        public Nullable<int> CausativeAgentCodeID { get; set; }
        public Nullable<int> ComplicationCodeID { get; set; }
        public string Severity { get; set; }
        public long AdmissionID { get; set; }
    
        public virtual Coded Tbl_Coded { get; set; }
        public virtual Syndromic Tbl_Syndromic { get; set; }
        public virtual Admission TblAdmission { get; set; }
    }
}
