//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorporatesHierarchy
    {
        public long CorporateId { get; set; }
        public Nullable<long> CenterCorporateId { get; set; }
        public Nullable<long> NetworkCorporateId { get; set; }
        public Nullable<long> UniversityCorporateId { get; set; }
        public string CenterCorporateName { get; set; }
        public string NetworkCorporateName { get; set; }
        public string UniversityCorporateName { get; set; }
        public string Province { get; set; }
        public Nullable<long> SubCenterCorporateId { get; set; }
        public string SubCenterCorporateName { get; set; }
    }
}
