//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corporate
    {
        public Corporate()
        {
            this.Samples = new HashSet<Sample>();
            this.TblTherosholds = new HashSet<Theroshold>();
            this.TblTherosholds1 = new HashSet<Theroshold>();
            this.LabDiseaseAssignments = new HashSet<LabDiseaseAssignment>();
            this.UserCorporatesHierarchies = new HashSet<UserCorporatesHierarchy>();
            this.UserCorporatesHierarchies1 = new HashSet<UserCorporatesHierarchy>();
            this.UserCorporatesHierarchies2 = new HashSet<UserCorporatesHierarchy>();
            this.UserCorporatesHierarchies3 = new HashSet<UserCorporatesHierarchy>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string EnName { get; set; }
        public string Description { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string Code { get; set; }
        public decimal FirstUserReg { get; set; }
        public string FirstDateReg { get; set; }
        public string IP { get; set; }
        public string ClientName { get; set; }
        public string City { get; set; }
        public string Provience { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
    
        public virtual ICollection<Sample> Samples { get; set; }
        public virtual ICollection<Theroshold> TblTherosholds { get; set; }
        public virtual ICollection<Theroshold> TblTherosholds1 { get; set; }
        public virtual ICollection<LabDiseaseAssignment> LabDiseaseAssignments { get; set; }
        public virtual ICollection<UserCorporatesHierarchy> UserCorporatesHierarchies { get; set; }
        public virtual ICollection<UserCorporatesHierarchy> UserCorporatesHierarchies1 { get; set; }
        public virtual ICollection<UserCorporatesHierarchy> UserCorporatesHierarchies2 { get; set; }
        public virtual ICollection<UserCorporatesHierarchy> UserCorporatesHierarchies3 { get; set; }
    }
}
