//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crtbl_Loan
    {
        public int id { get; set; }
        public Nullable<int> MaaliUserId { get; set; }
        public int LoanTypeId { get; set; }
        public int CustId { get; set; }
        public int CashierId { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<int> GiveBackTime { get; set; }
        public Nullable<bool> BranchBossOK { get; set; }
        public string BranchBossExplain { get; set; }
        public string MaaliUserExplain { get; set; }
        public Nullable<bool> MaaliUserOK { get; set; }
        public Nullable<bool> EtebariUserOK { get; set; }
        public string EtebariUserExplain { get; set; }
    
        public virtual Crtbl_CashierInfo Crtbl_CashierInfo { get; set; }
        public virtual Crtbl_CustInfo Crtbl_CustInfo { get; set; }
        public virtual Crtbl_LoanType Crtbl_LoanType { get; set; }
        public virtual Crtbl_MaaliUserInfo Crtbl_MaaliUserInfo { get; set; }
    }
}
