//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crtbl_BranchInfo
    {
        public Crtbl_BranchInfo()
        {
            this.Crtbl_BranchBossInfo = new HashSet<Crtbl_BranchBossInfo>();
            this.Crtbl_CashierInfo = new HashSet<Crtbl_CashierInfo>();
        }
    
        public int id { get; set; }
        public string BranchNo { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
    
        public virtual ICollection<Crtbl_BranchBossInfo> Crtbl_BranchBossInfo { get; set; }
        public virtual ICollection<Crtbl_CashierInfo> Crtbl_CashierInfo { get; set; }
    }
}
