//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crtbl_CustType
    {
        public Crtbl_CustType()
        {
            this.Crtbl_CustInfo = new HashSet<Crtbl_CustInfo>();
        }
    
        public int id { get; set; }
        public string CustType { get; set; }
    
        public virtual ICollection<Crtbl_CustInfo> Crtbl_CustInfo { get; set; }
    }
}
