//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crtbl_CustInfo
    {
        public Crtbl_CustInfo()
        {
            this.Crtbl_Loan = new HashSet<Crtbl_Loan>();
        }
    
        public int id { get; set; }
        public Nullable<double> CUSTINFOID { get; set; }
        public string CUSTNO { get; set; }
        public string CUSTOPNOF { get; set; }
        public int CustTypeId { get; set; }
        public string BRANCHNO { get; set; }
        public string DTBRTH { get; set; }
        public string MARSTAT { get; set; }
        public string DATEOPN { get; set; }
        public string NATCD { get; set; }
        public string RESTAT { get; set; }
        public string ISUCAP { get; set; }
        public string ESTPDTE { get; set; }
        public string COMPGNO { get; set; }
        public string IDNUMBER { get; set; }
        public string CUSUBTYP { get; set; }
        public string CUSTSAL { get; set; }
        public string DUPL_FLAG { get; set; }
        public string OCCUPCD { get; set; }
        public string SEXCODE { get; set; }
        public string SHRTNAM { get; set; }
        public string CUSENGN { get; set; }
        public string ARBNME { get; set; }
        public string MODIFDTE { get; set; }
        public string MODITIME { get; set; }
        public string PROFCODE { get; set; }
        public string FATHER_NAME { get; set; }
        public string ISSUED_TOWN { get; set; }
        public string SDRCODE { get; set; }
        public string ISSUED_DATE { get; set; }
        public string REGION_CODE { get; set; }
        public string ECONOMIC_CODE { get; set; }
        public string FAX_NUMBER { get; set; }
        public string EDUC_LVL { get; set; }
        public string NOOFPRTNR { get; set; }
        public string SHMELI { get; set; }
        public string address { get; set; }
        public string address2 { get; set; }
        public string FullName { get; set; }
        public string FirstNameCon { get; set; }
        public string LastNameCon { get; set; }
        public string FullNameCon { get; set; }
    
        public virtual Crtbl_CustType Crtbl_CustType { get; set; }
        public virtual ICollection<Crtbl_Loan> Crtbl_Loan { get; set; }
    }
}
