//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ctr_Risk
    {
        public int id { get; set; }
        public int RiskId { get; set; }
        public string Description { get; set; }
        public Nullable<int> CashierId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NationalCode { get; set; }
        public string CustomerCode { get; set; }
    
        public virtual Crtbl_CashierInfo Crtbl_CashierInfo { get; set; }
        public virtual Ctr_RiskCategory Ctr_RiskCategory { get; set; }
    }
}
