//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disease
    {
        public Disease()
        {
            this.LabBasicDatas = new HashSet<LabBasicData>();
            this.LabDiseasesCharacters = new HashSet<LabDiseasesCharacter>();
            this.LabResults = new HashSet<LabResult>();
            this.LabDiseaseAssignments = new HashSet<LabDiseaseAssignment>();
            this.ProAdmissions = new HashSet<ProAdmission>();
            this.TblDiseasesAccesses = new HashSet<TblDiseasesAccess>();
        }
    
        public int Id { get; set; }
        public string DiseasesName { get; set; }
        public string DiseasesPersianName { get; set; }
        public int SyndromId { get; set; }
        public string SnomedCode { get; set; }
        public string PositiveTitle { get; set; }
        public string Comment { get; set; }
        public Nullable<long> DiseaseCategoryId { get; set; }
    
        public virtual Syndromic Tbl_Syndromic { get; set; }
        public virtual ICollection<LabBasicData> LabBasicDatas { get; set; }
        public virtual ICollection<LabDiseasesCharacter> LabDiseasesCharacters { get; set; }
        public virtual ICollection<LabResult> LabResults { get; set; }
        public virtual ICollection<LabDiseaseAssignment> LabDiseaseAssignments { get; set; }
        public virtual ICollection<ProAdmission> ProAdmissions { get; set; }
        public virtual ICollection<TblDiseasesAccess> TblDiseasesAccesses { get; set; }
    }
}
