//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugTreatment
    {
        public long DrugTreatmentID { get; set; }
        public Nullable<int> DrugCodeID { get; set; }
        public string UseStartDate { get; set; }
        public string UseEndDate { get; set; }
        public Nullable<long> AdmissionID { get; set; }
    
        public virtual Coded Tbl_Coded { get; set; }
        public virtual Admission TblAdmission { get; set; }
    }
}
