//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugHistory
    {
        public long DrugHistoryID { get; set; }
        public long AdmissionID { get; set; }
        public Nullable<int> DrugCodeID { get; set; }
    
        public virtual Coded Tbl_Coded { get; set; }
        public virtual Admission TblAdmission { get; set; }
        public virtual DrugHistory TblDrugHistory1 { get; set; }
        public virtual DrugHistory TblDrugHistory2 { get; set; }
    }
}
