//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityEntityType
    {
        public int Id { get; set; }
        public Nullable<int> CorporateId { get; set; }
        public Nullable<int> CorporateTypeId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> PositionTypeId { get; set; }
        public Nullable<int> SystemId { get; set; }
        public Nullable<int> SystemTypeId { get; set; }
        public decimal FirstUserReg { get; set; }
        public string FirstDateReg { get; set; }
        public string IP { get; set; }
        public string ClientName { get; set; }
    
        public virtual EntityType EntityType { get; set; }
        public virtual EntityType EntityType1 { get; set; }
        public virtual Subsystem Subsystem { get; set; }
        public virtual EntityType EntityType2 { get; set; }
        public virtual Position Position { get; set; }
    }
}
