//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public long ErrorID { get; set; }
        public string CompositionUID { get; set; }
        public string Pateintuid { get; set; }
        public string ErrorDateTime { get; set; }
        public int CenterID { get; set; }
        public string ErrorMessage { get; set; }
    }
}
