//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetPatintInfo
    {
        public string FirstName { get; set; }
        public string NationalCode { get; set; }
        public string LastName { get; set; }
        public string BirthDate { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string FullAddress { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> Age { get; set; }
        public string AdmissionDate { get; set; }
        public Nullable<int> AdmissionType { get; set; }
        public string SamplingDate { get; set; }
        public string PostDate { get; set; }
        public string PaperCode { get; set; }
        public long PatientID { get; set; }
        public string Sex { get; set; }
        public string jobName { get; set; }
        public string NationalName { get; set; }
    }
}
