//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportUser
    {
        public string کد { get; set; }
        public string شبکه_بهداشتی { get; set; }
        public string نام { get; set; }
        public string نام_خانوادگی { get; set; }
        public string کد_ملی { get; set; }
        public string شماره_پرسنلی { get; set; }
        public string پست_سازمانی { get; set; }
        public string ایمیل { get; set; }
        public string شماره_موبایل { get; set; }
        public int Id { get; set; }
    }
}
