//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoBaseValue
    {
        public InfoBaseValue()
        {
            this.InfoBaseValue1 = new HashSet<InfoBaseValue>();
        }
    
        public decimal InfoBaseValueID { get; set; }
        public decimal InfoBaseID_Fk { get; set; }
        public Nullable<decimal> BaseValueParent { get; set; }
        public string NameValue { get; set; }
        public decimal Sort { get; set; }
        public bool Active { get; set; }
        public decimal FirstUserReg { get; set; }
        public string FirstDateReg { get; set; }
        public string IP { get; set; }
        public string ClientName { get; set; }
    
        public virtual InfoBase InfoBase { get; set; }
        public virtual ICollection<InfoBaseValue> InfoBaseValue1 { get; set; }
        public virtual InfoBaseValue InfoBaseValue2 { get; set; }
    }
}
