//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoBase
    {
        public InfoBase()
        {
            this.InfoBaseValues = new HashSet<InfoBaseValue>();
        }
    
        public decimal InfoBaseID { get; set; }
        public decimal ParentCode { get; set; }
        public string NameSefat { get; set; }
    
        public virtual ICollection<InfoBaseValue> InfoBaseValues { get; set; }
    }
}
