//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    
    public partial class MiniCenterType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string CenterTypeUniqId { get; set; }
        public int FieldOfView { get; set; }
        public Nullable<int> Special { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> StructureOrder { get; set; }
        public int ParentId { get; set; }
    }
}
