//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSG
    {
        public MSG()
        {
            this.TblMSG_Admission = new HashSet<MSG_Admission>();
        }
    
        public long MsgID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NationalCode { get; set; }
        public string healthCareFacility { get; set; }
        public Nullable<long> AdmissionID { get; set; }
    
        public virtual ICollection<MSG_Admission> TblMSG_Admission { get; set; }
    }
}
