//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperCode
    {
        public long PaperCodeID { get; set; }
        public string CenterGUID { get; set; }
        public System.DateTime RegisterDate { get; set; }
    }
}
