//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProAdmissionDoneStep
    {
        public int ProAdmissionDoneStepId { get; set; }
        public int ProAdmissionId { get; set; }
        public string Date { get; set; }
        public int UserId { get; set; }
        public long StepId { get; set; }
        public bool Skipped { get; set; }
    
        public virtual BasicData BasicData { get; set; }
        public virtual ProAdmission ProAdmission { get; set; }
    }
}
