//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProAdmission
    {
        public ProAdmission()
        {
            this.ProClinicalFindings = new HashSet<ProClinicalFinding>();
            this.ProDiagnosis = new HashSet<ProDiagnosi>();
            this.ProDrugHistories = new HashSet<ProDrugHistory>();
            this.ProLabs = new HashSet<ProLab>();
            this.ProPastMedicalHistories = new HashSet<ProPastMedicalHistory>();
            this.ProTravels = new HashSet<ProTravel>();
            this.Samples = new HashSet<Sample>();
            this.ProAdmissionDoneSteps = new HashSet<ProAdmissionDoneStep>();
            this.ThresholdWarningStatus = new HashSet<ThresholdWarningStatu>();
        }
    
        public int AdmissionID { get; set; }
        public string AdmissionDate { get; set; }
        public Nullable<System.DateTime> AdmissionTime { get; set; }
        public Nullable<int> AdmissionType { get; set; }
        public Nullable<int> InstituteID { get; set; }
        public string MedicalRecordNumber { get; set; }
        public Nullable<int> ReasonforEncounter { get; set; }
        public Nullable<long> PatientID { get; set; }
        public string PaperCode { get; set; }
        public string FinishDate { get; set; }
        public string PostDate { get; set; }
        public string SamplingDate { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public string CompositionUID { get; set; }
        public string RefferingDoctor { get; set; }
        public string Discharge { get; set; }
        public Nullable<int> DischargeCode { get; set; }
        public string RegisterDate { get; set; }
        public Nullable<int> SyndromId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> Indirect { get; set; }
        public Nullable<int> BestLabResultId { get; set; }
        public Nullable<int> BestLabResultDiseaseId { get; set; }
        public bool IsTransferedToSepas { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ProClinicalFinding> ProClinicalFindings { get; set; }
        public virtual ICollection<ProDiagnosi> ProDiagnosis { get; set; }
        public virtual ICollection<ProDrugHistory> ProDrugHistories { get; set; }
        public virtual ICollection<ProLab> ProLabs { get; set; }
        public virtual ICollection<ProPastMedicalHistory> ProPastMedicalHistories { get; set; }
        public virtual ICollection<ProTravel> ProTravels { get; set; }
        public virtual ICollection<Sample> Samples { get; set; }
        public virtual ICollection<ProAdmissionDoneStep> ProAdmissionDoneSteps { get; set; }
        public virtual ICollection<ThresholdWarningStatu> ThresholdWarningStatus { get; set; }
        public virtual Disease Disease { get; set; }
    }
}
