//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProCoded
    {
        public int CodeID { get; set; }
        public string terminologyid { get; set; }
        public string CodeType { get; set; }
        public string coded { get; set; }
        public string valuee { get; set; }
        public string english { get; set; }
        public string EnglishTerm { get; set; }
    }
}
