//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProPaperCode
    {
        public int ID { get; set; }
        public string PaperCodeID { get; set; }
        public Nullable<System.DateTime> GetDateTime { get; set; }
        public Nullable<bool> IsPrint { get; set; }
        public Nullable<System.DateTime> Printdatetime { get; set; }
        public Nullable<int> SyndromicId { get; set; }
        public Nullable<int> CenterID { get; set; }
    }
}
