//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProReaction
    {
        public int AdverseReactionID { get; set; }
        public Nullable<int> AdverseCodeID { get; set; }
        public Nullable<int> ReactionCodeID { get; set; }
        public string severity { get; set; }
        public string AdmissionID { get; set; }
    }
}
