//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProTravel
    {
        public int TravelID { get; set; }
        public Nullable<int> AdmissionID { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> AreLocationID { get; set; }
        public Nullable<bool> BirdHistory { get; set; }
        public bool IndirectAbroadTouch { get; set; }
    
        public virtual AreaLocation Tbl_AreaLocation { get; set; }
        public virtual Country Tbl_Country { get; set; }
        public virtual ProAdmission ProAdmission { get; set; }
    }
}
