//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public int GroupId { get; set; }
        public int PositionId { get; set; }
        public int FirstUserReg { get; set; }
        public string FirstDateReg { get; set; }
        public string IP { get; set; }
        public string ClientName { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
