//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyndromRegister
    {
        public long SyndromRegisterId { get; set; }
        public Nullable<long> PatientID { get; set; }
        public Nullable<int> SyndromicId { get; set; }
        public string PersianDate { get; set; }
        public Nullable<System.DateTime> RegisterDateTime { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> IsOutRegister { get; set; }
        public Nullable<int> AdmissionType { get; set; }
        public Nullable<bool> IsTransferSepas { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> ErrorTime { get; set; }
        public string CompositionUID { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<bool> Alert { get; set; }
        public Nullable<bool> IsPro { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public bool IsTransferedToSepas { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
