//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDiseasesAccess
    {
        public int Id { get; set; }
        public int DiseasesId { get; set; }
        public int PositionsId { get; set; }
    
        public virtual Disease Disease { get; set; }
        public virtual Position Position { get; set; }
    }
}
