//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theroshold
    {
        public Theroshold()
        {
            this.WarningThresholds = new HashSet<WarningThreshold>();
        }
    
        public int TherosholdID { get; set; }
        public long MethodID { get; set; }
        public Nullable<decimal> FixNumber { get; set; }
        public int SyndromicId { get; set; }
        public int ProvinceId { get; set; }
        public long UniversityId { get; set; }
        public long NetworkId { get; set; }
        public Nullable<long> PreProcessMethod { get; set; }
        public bool PercentBased { get; set; }
        public Nullable<double> Factor { get; set; }
        public bool Deleted { get; set; }
        public Nullable<decimal> MinAbsoluteLimit { get; set; }
    
        public virtual AreaLocation Tbl_AreaLocation { get; set; }
        public virtual Syndromic Tbl_Syndromic { get; set; }
        public virtual BasicData BasicData { get; set; }
        public virtual BasicData BasicData1 { get; set; }
        public virtual Corporate Corporate { get; set; }
        public virtual Corporate Corporate1 { get; set; }
        public virtual ICollection<WarningThreshold> WarningThresholds { get; set; }
    }
}
