//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThresholdWarningReceiver
    {
        public int Id { get; set; }
        public int ThresholdWarningId { get; set; }
        public int ReceiverUserId { get; set; }
        public long SmsId { get; set; }
        public System.DateTime RegisterDateTime { get; set; }
        public string PersianDate { get; set; }
    
        public virtual SmsLog TblSmsLog { get; set; }
        public virtual User User { get; set; }
        public virtual WarningThreshold WarningThreshold { get; set; }
    }
}
