//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NewUserManagementEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NewUserManagementEntities object using the connection string found in the 'NewUserManagementEntities' section of the application configuration file.
        /// </summary>
        public NewUserManagementEntities() : base("name=NewUserManagementEntities", "NewUserManagementEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NewUserManagementEntities object.
        /// </summary>
        public NewUserManagementEntities(string connectionString) : base(connectionString, "NewUserManagementEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NewUserManagementEntities object.
        /// </summary>
        public NewUserManagementEntities(EntityConnection connection) : base(connection, "NewUserManagementEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Corporate> Corporates
        {
            get
            {
                if ((_Corporates == null))
                {
                    _Corporates = base.CreateObjectSet<Corporate>("Corporates");
                }
                return _Corporates;
            }
        }
        private ObjectSet<Corporate> _Corporates;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Corporates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCorporates(Corporate corporate)
        {
            base.AddObject("Corporates", corporate);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="name">No Metadata Documentation available.</param>
        /// <param name="code">No Metadata Documentation available.</param>
        /// <param name="areaCode">No Metadata Documentation available.</param>
        public ObjectResult<Corporate> FindeBranches(global::System.String name, Nullable<global::System.Int32> code, Nullable<global::System.Int32> areaCode)
        {
            ObjectParameter nameParameter;
            if (name != null)
            {
                nameParameter = new ObjectParameter("Name", name);
            }
            else
            {
                nameParameter = new ObjectParameter("Name", typeof(global::System.String));
            }
    
            ObjectParameter codeParameter;
            if (code.HasValue)
            {
                codeParameter = new ObjectParameter("Code", code);
            }
            else
            {
                codeParameter = new ObjectParameter("Code", typeof(global::System.Int32));
            }
    
            ObjectParameter areaCodeParameter;
            if (areaCode.HasValue)
            {
                areaCodeParameter = new ObjectParameter("AreaCode", areaCode);
            }
            else
            {
                areaCodeParameter = new ObjectParameter("AreaCode", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<Corporate>("FindeBranches", nameParameter, codeParameter, areaCodeParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="name">No Metadata Documentation available.</param>
        /// <param name="code">No Metadata Documentation available.</param>
        /// <param name="areaCode">No Metadata Documentation available.</param>
        public ObjectResult<Corporate> FindeBranches(global::System.String name, Nullable<global::System.Int32> code, Nullable<global::System.Int32> areaCode, MergeOption mergeOption)
        {
            ObjectParameter nameParameter;
            if (name != null)
            {
                nameParameter = new ObjectParameter("Name", name);
            }
            else
            {
                nameParameter = new ObjectParameter("Name", typeof(global::System.String));
            }
    
            ObjectParameter codeParameter;
            if (code.HasValue)
            {
                codeParameter = new ObjectParameter("Code", code);
            }
            else
            {
                codeParameter = new ObjectParameter("Code", typeof(global::System.Int32));
            }
    
            ObjectParameter areaCodeParameter;
            if (areaCode.HasValue)
            {
                areaCodeParameter = new ObjectParameter("AreaCode", areaCode);
            }
            else
            {
                areaCodeParameter = new ObjectParameter("AreaCode", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<Corporate>("FindeBranches", mergeOption, nameParameter, codeParameter, areaCodeParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="areaCode">No Metadata Documentation available.</param>
        public ObjectResult<Corporate> GetAreaCode(Nullable<global::System.Int64> areaCode)
        {
            ObjectParameter areaCodeParameter;
            if (areaCode.HasValue)
            {
                areaCodeParameter = new ObjectParameter("AreaCode", areaCode);
            }
            else
            {
                areaCodeParameter = new ObjectParameter("AreaCode", typeof(global::System.Int64));
            }
    
            return base.ExecuteFunction<Corporate>("GetAreaCode", areaCodeParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="areaCode">No Metadata Documentation available.</param>
        public ObjectResult<Corporate> GetAreaCode(Nullable<global::System.Int64> areaCode, MergeOption mergeOption)
        {
            ObjectParameter areaCodeParameter;
            if (areaCode.HasValue)
            {
                areaCodeParameter = new ObjectParameter("AreaCode", areaCode);
            }
            else
            {
                areaCodeParameter = new ObjectParameter("AreaCode", typeof(global::System.Int64));
            }
    
            return base.ExecuteFunction<Corporate>("GetAreaCode", mergeOption, areaCodeParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="areacode">No Metadata Documentation available.</param>
        public ObjectResult<Corporate> GetShoab(Nullable<global::System.Int64> areacode)
        {
            ObjectParameter areacodeParameter;
            if (areacode.HasValue)
            {
                areacodeParameter = new ObjectParameter("Areacode", areacode);
            }
            else
            {
                areacodeParameter = new ObjectParameter("Areacode", typeof(global::System.Int64));
            }
    
            return base.ExecuteFunction<Corporate>("GetShoab", areacodeParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="areacode">No Metadata Documentation available.</param>
        public ObjectResult<Corporate> GetShoab(Nullable<global::System.Int64> areacode, MergeOption mergeOption)
        {
            ObjectParameter areacodeParameter;
            if (areacode.HasValue)
            {
                areacodeParameter = new ObjectParameter("Areacode", areacode);
            }
            else
            {
                areacodeParameter = new ObjectParameter("Areacode", typeof(global::System.Int64));
            }
    
            return base.ExecuteFunction<Corporate>("GetShoab", mergeOption, areacodeParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="areaCode">No Metadata Documentation available.</param>
        public ObjectResult<Corporate> GetZoneCode(Nullable<global::System.Int64> areaCode)
        {
            ObjectParameter areaCodeParameter;
            if (areaCode.HasValue)
            {
                areaCodeParameter = new ObjectParameter("AreaCode", areaCode);
            }
            else
            {
                areaCodeParameter = new ObjectParameter("AreaCode", typeof(global::System.Int64));
            }
    
            return base.ExecuteFunction<Corporate>("GetZoneCode", areaCodeParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="areaCode">No Metadata Documentation available.</param>
        public ObjectResult<Corporate> GetZoneCode(Nullable<global::System.Int64> areaCode, MergeOption mergeOption)
        {
            ObjectParameter areaCodeParameter;
            if (areaCode.HasValue)
            {
                areaCodeParameter = new ObjectParameter("AreaCode", areaCode);
            }
            else
            {
                areaCodeParameter = new ObjectParameter("AreaCode", typeof(global::System.Int64));
            }
    
            return base.ExecuteFunction<Corporate>("GetZoneCode", mergeOption, areaCodeParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SyndromicModel1", Name="Corporate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Corporate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Corporate object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="enName">Initial value of the EnName property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="firstUserReg">Initial value of the FirstUserReg property.</param>
        /// <param name="firstDateReg">Initial value of the FirstDateReg property.</param>
        /// <param name="iP">Initial value of the IP property.</param>
        /// <param name="clientName">Initial value of the ClientName property.</param>
        public static Corporate CreateCorporate(global::System.Int64 id, global::System.String name, global::System.String enName, global::System.String description, global::System.String code, global::System.Decimal firstUserReg, global::System.String firstDateReg, global::System.String iP, global::System.String clientName)
        {
            Corporate corporate = new Corporate();
            corporate.Id = id;
            corporate.Name = name;
            corporate.EnName = enName;
            corporate.Description = description;
            corporate.Code = code;
            corporate.FirstUserReg = firstUserReg;
            corporate.FirstDateReg = firstDateReg;
            corporate.IP = iP;
            corporate.ClientName = clientName;
            return corporate;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EnName
        {
            get
            {
                return _EnName;
            }
            set
            {
                OnEnNameChanging(value);
                ReportPropertyChanging("EnName");
                _EnName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EnName");
                OnEnNameChanged();
            }
        }
        private global::System.String _EnName;
        partial void OnEnNameChanging(global::System.String value);
        partial void OnEnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int64> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int64> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal FirstUserReg
        {
            get
            {
                return _FirstUserReg;
            }
            set
            {
                OnFirstUserRegChanging(value);
                ReportPropertyChanging("FirstUserReg");
                _FirstUserReg = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FirstUserReg");
                OnFirstUserRegChanged();
            }
        }
        private global::System.Decimal _FirstUserReg;
        partial void OnFirstUserRegChanging(global::System.Decimal value);
        partial void OnFirstUserRegChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstDateReg
        {
            get
            {
                return _FirstDateReg;
            }
            set
            {
                OnFirstDateRegChanging(value);
                ReportPropertyChanging("FirstDateReg");
                _FirstDateReg = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstDateReg");
                OnFirstDateRegChanged();
            }
        }
        private global::System.String _FirstDateReg;
        partial void OnFirstDateRegChanging(global::System.String value);
        partial void OnFirstDateRegChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClientName
        {
            get
            {
                return _ClientName;
            }
            set
            {
                OnClientNameChanging(value);
                ReportPropertyChanging("ClientName");
                _ClientName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClientName");
                OnClientNameChanged();
            }
        }
        private global::System.String _ClientName;
        partial void OnClientNameChanging(global::System.String value);
        partial void OnClientNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Provience
        {
            get
            {
                return _Provience;
            }
            set
            {
                OnProvienceChanging(value);
                ReportPropertyChanging("Provience");
                _Provience = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Provience");
                OnProvienceChanged();
            }
        }
        private global::System.String _Provience;
        partial void OnProvienceChanging(global::System.String value);
        partial void OnProvienceChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SyndromicModel1", Name="FindeBranches_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class FindeBranches_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FindeBranches_Result object.
        /// </summary>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="enName">Initial value of the EnName property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="firstUserReg">Initial value of the FirstUserReg property.</param>
        /// <param name="firstDateReg">Initial value of the FirstDateReg property.</param>
        /// <param name="iP">Initial value of the IP property.</param>
        /// <param name="clientName">Initial value of the ClientName property.</param>
        public static FindeBranches_Result CreateFindeBranches_Result(global::System.String name, global::System.String enName, global::System.String description, global::System.String code, global::System.Decimal firstUserReg, global::System.String firstDateReg, global::System.String iP, global::System.String clientName)
        {
            FindeBranches_Result findeBranches_Result = new FindeBranches_Result();
            findeBranches_Result.Name = name;
            findeBranches_Result.EnName = enName;
            findeBranches_Result.Description = description;
            findeBranches_Result.Code = code;
            findeBranches_Result.FirstUserReg = firstUserReg;
            findeBranches_Result.FirstDateReg = firstDateReg;
            findeBranches_Result.IP = iP;
            findeBranches_Result.ClientName = clientName;
            return findeBranches_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private Nullable<global::System.Int64> _Id;
        partial void OnIdChanging(Nullable<global::System.Int64> value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EnName
        {
            get
            {
                return _EnName;
            }
            set
            {
                OnEnNameChanging(value);
                ReportPropertyChanging("EnName");
                _EnName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EnName");
                OnEnNameChanged();
            }
        }
        private global::System.String _EnName;
        partial void OnEnNameChanging(global::System.String value);
        partial void OnEnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int64> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int64> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal FirstUserReg
        {
            get
            {
                return _FirstUserReg;
            }
            set
            {
                OnFirstUserRegChanging(value);
                ReportPropertyChanging("FirstUserReg");
                _FirstUserReg = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FirstUserReg");
                OnFirstUserRegChanged();
            }
        }
        private global::System.Decimal _FirstUserReg;
        partial void OnFirstUserRegChanging(global::System.Decimal value);
        partial void OnFirstUserRegChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstDateReg
        {
            get
            {
                return _FirstDateReg;
            }
            set
            {
                OnFirstDateRegChanging(value);
                ReportPropertyChanging("FirstDateReg");
                _FirstDateReg = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstDateReg");
                OnFirstDateRegChanged();
            }
        }
        private global::System.String _FirstDateReg;
        partial void OnFirstDateRegChanging(global::System.String value);
        partial void OnFirstDateRegChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClientName
        {
            get
            {
                return _ClientName;
            }
            set
            {
                OnClientNameChanging(value);
                ReportPropertyChanging("ClientName");
                _ClientName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClientName");
                OnClientNameChanged();
            }
        }
        private global::System.String _ClientName;
        partial void OnClientNameChanging(global::System.String value);
        partial void OnClientNameChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SyndromicModel1", Name="GetAreaCode_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetAreaCode_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetAreaCode_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="enName">Initial value of the EnName property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="firstUserReg">Initial value of the FirstUserReg property.</param>
        /// <param name="firstDateReg">Initial value of the FirstDateReg property.</param>
        /// <param name="iP">Initial value of the IP property.</param>
        /// <param name="clientName">Initial value of the ClientName property.</param>
        public static GetAreaCode_Result CreateGetAreaCode_Result(global::System.Int64 id, global::System.String name, global::System.String enName, global::System.String description, global::System.String code, global::System.Decimal firstUserReg, global::System.String firstDateReg, global::System.String iP, global::System.String clientName)
        {
            GetAreaCode_Result getAreaCode_Result = new GetAreaCode_Result();
            getAreaCode_Result.Id = id;
            getAreaCode_Result.Name = name;
            getAreaCode_Result.EnName = enName;
            getAreaCode_Result.Description = description;
            getAreaCode_Result.Code = code;
            getAreaCode_Result.FirstUserReg = firstUserReg;
            getAreaCode_Result.FirstDateReg = firstDateReg;
            getAreaCode_Result.IP = iP;
            getAreaCode_Result.ClientName = clientName;
            return getAreaCode_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EnName
        {
            get
            {
                return _EnName;
            }
            set
            {
                OnEnNameChanging(value);
                ReportPropertyChanging("EnName");
                _EnName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EnName");
                OnEnNameChanged();
            }
        }
        private global::System.String _EnName;
        partial void OnEnNameChanging(global::System.String value);
        partial void OnEnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int64> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int64> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal FirstUserReg
        {
            get
            {
                return _FirstUserReg;
            }
            set
            {
                OnFirstUserRegChanging(value);
                ReportPropertyChanging("FirstUserReg");
                _FirstUserReg = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FirstUserReg");
                OnFirstUserRegChanged();
            }
        }
        private global::System.Decimal _FirstUserReg;
        partial void OnFirstUserRegChanging(global::System.Decimal value);
        partial void OnFirstUserRegChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstDateReg
        {
            get
            {
                return _FirstDateReg;
            }
            set
            {
                OnFirstDateRegChanging(value);
                ReportPropertyChanging("FirstDateReg");
                _FirstDateReg = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstDateReg");
                OnFirstDateRegChanged();
            }
        }
        private global::System.String _FirstDateReg;
        partial void OnFirstDateRegChanging(global::System.String value);
        partial void OnFirstDateRegChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClientName
        {
            get
            {
                return _ClientName;
            }
            set
            {
                OnClientNameChanging(value);
                ReportPropertyChanging("ClientName");
                _ClientName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClientName");
                OnClientNameChanged();
            }
        }
        private global::System.String _ClientName;
        partial void OnClientNameChanging(global::System.String value);
        partial void OnClientNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Provience
        {
            get
            {
                return _Provience;
            }
            set
            {
                OnProvienceChanging(value);
                ReportPropertyChanging("Provience");
                _Provience = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Provience");
                OnProvienceChanged();
            }
        }
        private global::System.String _Provience;
        partial void OnProvienceChanging(global::System.String value);
        partial void OnProvienceChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SyndromicModel1", Name="GetShoab_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetShoab_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetShoab_Result object.
        /// </summary>
        /// <param name="id1">Initial value of the Id1 property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="enName">Initial value of the EnName property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="firstUserReg">Initial value of the FirstUserReg property.</param>
        /// <param name="firstDateReg">Initial value of the FirstDateReg property.</param>
        /// <param name="iP">Initial value of the IP property.</param>
        /// <param name="clientName">Initial value of the ClientName property.</param>
        public static GetShoab_Result CreateGetShoab_Result(global::System.Int64 id1, global::System.String name, global::System.String enName, global::System.String description, global::System.String code, global::System.Decimal firstUserReg, global::System.String firstDateReg, global::System.String iP, global::System.String clientName)
        {
            GetShoab_Result getShoab_Result = new GetShoab_Result();
            getShoab_Result.Id1 = id1;
            getShoab_Result.Name = name;
            getShoab_Result.EnName = enName;
            getShoab_Result.Description = description;
            getShoab_Result.Code = code;
            getShoab_Result.FirstUserReg = firstUserReg;
            getShoab_Result.FirstDateReg = firstDateReg;
            getShoab_Result.IP = iP;
            getShoab_Result.ClientName = clientName;
            return getShoab_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Column1
        {
            get
            {
                return _Column1;
            }
            set
            {
                OnColumn1Changing(value);
                ReportPropertyChanging("Column1");
                _Column1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Column1");
                OnColumn1Changed();
            }
        }
        private Nullable<global::System.Int32> _Column1;
        partial void OnColumn1Changing(Nullable<global::System.Int32> value);
        partial void OnColumn1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id1
        {
            get
            {
                return _Id1;
            }
            set
            {
                OnId1Changing(value);
                ReportPropertyChanging("Id1");
                _Id1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id1");
                OnId1Changed();
            }
        }
        private global::System.Int64 _Id1;
        partial void OnId1Changing(global::System.Int64 value);
        partial void OnId1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EnName
        {
            get
            {
                return _EnName;
            }
            set
            {
                OnEnNameChanging(value);
                ReportPropertyChanging("EnName");
                _EnName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EnName");
                OnEnNameChanged();
            }
        }
        private global::System.String _EnName;
        partial void OnEnNameChanging(global::System.String value);
        partial void OnEnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int64> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int64> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal FirstUserReg
        {
            get
            {
                return _FirstUserReg;
            }
            set
            {
                OnFirstUserRegChanging(value);
                ReportPropertyChanging("FirstUserReg");
                _FirstUserReg = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FirstUserReg");
                OnFirstUserRegChanged();
            }
        }
        private global::System.Decimal _FirstUserReg;
        partial void OnFirstUserRegChanging(global::System.Decimal value);
        partial void OnFirstUserRegChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstDateReg
        {
            get
            {
                return _FirstDateReg;
            }
            set
            {
                OnFirstDateRegChanging(value);
                ReportPropertyChanging("FirstDateReg");
                _FirstDateReg = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstDateReg");
                OnFirstDateRegChanged();
            }
        }
        private global::System.String _FirstDateReg;
        partial void OnFirstDateRegChanging(global::System.String value);
        partial void OnFirstDateRegChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClientName
        {
            get
            {
                return _ClientName;
            }
            set
            {
                OnClientNameChanging(value);
                ReportPropertyChanging("ClientName");
                _ClientName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClientName");
                OnClientNameChanged();
            }
        }
        private global::System.String _ClientName;
        partial void OnClientNameChanging(global::System.String value);
        partial void OnClientNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Provience
        {
            get
            {
                return _Provience;
            }
            set
            {
                OnProvienceChanging(value);
                ReportPropertyChanging("Provience");
                _Provience = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Provience");
                OnProvienceChanged();
            }
        }
        private global::System.String _Provience;
        partial void OnProvienceChanging(global::System.String value);
        partial void OnProvienceChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SyndromicModel1", Name="GetZoneCode_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetZoneCode_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetZoneCode_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="enName">Initial value of the EnName property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="firstUserReg">Initial value of the FirstUserReg property.</param>
        /// <param name="firstDateReg">Initial value of the FirstDateReg property.</param>
        /// <param name="iP">Initial value of the IP property.</param>
        /// <param name="clientName">Initial value of the ClientName property.</param>
        public static GetZoneCode_Result CreateGetZoneCode_Result(global::System.Int64 id, global::System.String name, global::System.String enName, global::System.String description, global::System.String code, global::System.Decimal firstUserReg, global::System.String firstDateReg, global::System.String iP, global::System.String clientName)
        {
            GetZoneCode_Result getZoneCode_Result = new GetZoneCode_Result();
            getZoneCode_Result.Id = id;
            getZoneCode_Result.Name = name;
            getZoneCode_Result.EnName = enName;
            getZoneCode_Result.Description = description;
            getZoneCode_Result.Code = code;
            getZoneCode_Result.FirstUserReg = firstUserReg;
            getZoneCode_Result.FirstDateReg = firstDateReg;
            getZoneCode_Result.IP = iP;
            getZoneCode_Result.ClientName = clientName;
            return getZoneCode_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EnName
        {
            get
            {
                return _EnName;
            }
            set
            {
                OnEnNameChanging(value);
                ReportPropertyChanging("EnName");
                _EnName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EnName");
                OnEnNameChanged();
            }
        }
        private global::System.String _EnName;
        partial void OnEnNameChanging(global::System.String value);
        partial void OnEnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int64> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int64> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal FirstUserReg
        {
            get
            {
                return _FirstUserReg;
            }
            set
            {
                OnFirstUserRegChanging(value);
                ReportPropertyChanging("FirstUserReg");
                _FirstUserReg = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FirstUserReg");
                OnFirstUserRegChanged();
            }
        }
        private global::System.Decimal _FirstUserReg;
        partial void OnFirstUserRegChanging(global::System.Decimal value);
        partial void OnFirstUserRegChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstDateReg
        {
            get
            {
                return _FirstDateReg;
            }
            set
            {
                OnFirstDateRegChanging(value);
                ReportPropertyChanging("FirstDateReg");
                _FirstDateReg = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstDateReg");
                OnFirstDateRegChanged();
            }
        }
        private global::System.String _FirstDateReg;
        partial void OnFirstDateRegChanging(global::System.String value);
        partial void OnFirstDateRegChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClientName
        {
            get
            {
                return _ClientName;
            }
            set
            {
                OnClientNameChanging(value);
                ReportPropertyChanging("ClientName");
                _ClientName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClientName");
                OnClientNameChanged();
            }
        }
        private global::System.String _ClientName;
        partial void OnClientNameChanging(global::System.String value);
        partial void OnClientNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Provience
        {
            get
            {
                return _Provience;
            }
            set
            {
                OnProvienceChanging(value);
                ReportPropertyChanging("Provience");
                _Provience = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Provience");
                OnProvienceChanged();
            }
        }
        private global::System.String _Provience;
        partial void OnProvienceChanging(global::System.String value);
        partial void OnProvienceChanged();

        #endregion

    }

    #endregion

    
}
