//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCorporatesHierarchy
    {
        public int UserId { get; set; }
        public long CorporateId { get; set; }
        public Nullable<long> CenterCorporateId { get; set; }
        public Nullable<long> NetworkCorporateId { get; set; }
        public Nullable<long> UniversityCorporateId { get; set; }
        public string CenterCorporateName { get; set; }
        public string NetworkCorporateName { get; set; }
        public string UniversityCorporateName { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<long> SubCenterCorporateId { get; set; }
        public string SubCenterCorporateName { get; set; }
    
        public virtual Corporate Corporate { get; set; }
        public virtual Corporate Corporate1 { get; set; }
        public virtual Corporate Corporate2 { get; set; }
        public virtual Corporate Corporate3 { get; set; }
        public virtual User User { get; set; }
    }
}
