//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitCount
    {
        public long VisitID { get; set; }
        public Nullable<System.DateTime> RegisterDateTime { get; set; }
        public string PersianDate { get; set; }
        public long UserId { get; set; }
        public int Number { get; set; }
        public Nullable<int> RegistererUserId { get; set; }
        public Nullable<long> CorporateId { get; set; }
    }
}
