//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TempEfHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeathLocation
    {
        public DeathLocation()
        {
            this.TblDeaths = new HashSet<TblDeath>();
        }
    
        public int Id { get; set; }
        public string deathLocation1 { get; set; }
    
        public virtual ICollection<TblDeath> TblDeaths { get; set; }
    }
}
