//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TempEfHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabBasicData
    {
        public LabBasicData()
        {
            this.LabBasicData1 = new HashSet<LabBasicData>();
            this.LabDetailResults = new HashSet<LabDetailResult>();
        }
    
        public long Id { get; set; }
        public Nullable<long> BasicDataTypeId { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string Title { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> DiseasesId { get; set; }
        public string SnomedCode { get; set; }
        public string TerminologyID { get; set; }
    
        public virtual BasicDataType BasicDataType { get; set; }
        public virtual Disease Disease { get; set; }
        public virtual ICollection<LabBasicData> LabBasicData1 { get; set; }
        public virtual LabBasicData LabBasicData2 { get; set; }
        public virtual ICollection<LabDetailResult> LabDetailResults { get; set; }
    }
}
