//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TempEfHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabResult
    {
        public LabResult()
        {
            this.LabDetailResults = new HashSet<LabDetailResult>();
        }
    
        public int Id { get; set; }
        public string ReciveLLabTestDate { get; set; }
        public int UserId { get; set; }
        public int AdmissionId { get; set; }
        public string LabResultDate { get; set; }
        public int DiseasesId { get; set; }
        public int Testquality { get; set; }
        public int PrimaryLabResult { get; set; }
        public System.DateTime CurrentDateTime { get; set; }
    
        public virtual Disease Disease { get; set; }
        public virtual ICollection<LabDetailResult> LabDetailResults { get; set; }
        public virtual ProAdmission ProAdmission { get; set; }
    }
}
