//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TempEfHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public long Id { get; set; }
        public string OrganizationID { get; set; }
        public string LongName { get; set; }
        public string OrganizationTypeCode { get; set; }
        public string OrganizationTypeValue { get; set; }
        public string SupervisorUniversityID { get; set; }
        public string SupervisorLongName { get; set; }
        public string ActivationStatusCode { get; set; }
        public string ActivationStatusValue { get; set; }
        public string OwnerTypeValue { get; set; }
        public string PostalCode { get; set; }
        public string FullAddress { get; set; }
        public string CountryDivisionsCode { get; set; }
        public string CountryDivisionsValue { get; set; }
        public string AreaTypeCode { get; set; }
        public string Province { get; set; }
        public string ProvinceCode { get; set; }
        public string Township { get; set; }
        public string TownshipCode { get; set; }
        public string City { get; set; }
        public string CityCode { get; set; }
        public string County { get; set; }
        public string CountyCode { get; set; }
        public string RuralDistinctCode { get; set; }
        public string RuralDistinct { get; set; }
    }
}
