//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TempEfHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public Position()
        {
            this.EntityEntityTypes = new HashSet<EntityEntityType>();
            this.Positions1 = new HashSet<Position>();
            this.Rules = new HashSet<Rule>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
        public decimal FirstUserReg { get; set; }
        public string FirstDateReg { get; set; }
        public string IP { get; set; }
        public string ClientName { get; set; }
    
        public virtual ICollection<EntityEntityType> EntityEntityTypes { get; set; }
        public virtual ICollection<Position> Positions1 { get; set; }
        public virtual Position Position1 { get; set; }
        public virtual ICollection<Rule> Rules { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
