//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TempEfHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProCenter
    {
        public int ID { get; set; }
        public string CenterName { get; set; }
        public string CenterGUID { get; set; }
        public string UniversityName { get; set; }
        public string provinceName { get; set; }
        public string CityName { get; set; }
        public string TownName { get; set; }
        public string RuralAreaName { get; set; }
        public string PostalCode { get; set; }
        public string FullAddress { get; set; }
        public string Centertype { get; set; }
        public Nullable<bool> IsDisabeld { get; set; }
    }
}
