//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TempEfHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProChiefComplaint
    {
        public int ChiefComplaintID { get; set; }
        public Nullable<int> SymptomsID { get; set; }
        public string DateofOnset { get; set; }
        public Nullable<int> AdmissionID { get; set; }
    }
}
