//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TempEfHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProDrugHistory
    {
        public int DrugHistoryID { get; set; }
        public Nullable<int> AdmissionID { get; set; }
        public Nullable<int> DrugCodeID { get; set; }
    
        public virtual Tbl_Coded Tbl_Coded { get; set; }
        public virtual ProAdmission ProAdmission { get; set; }
    }
}
