//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TempEfHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subsystem
    {
        public Subsystem()
        {
            this.EntityEntityTypes = new HashSet<EntityEntityType>();
            this.Permissions = new HashSet<Permission>();
            this.UserGroups = new HashSet<UserGroup>();
            this.UsersRoles = new HashSet<UsersRole>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal FirstUserReg { get; set; }
        public string FirstDateReg { get; set; }
        public string IP { get; set; }
        public string ClientName { get; set; }
    
        public virtual ICollection<EntityEntityType> EntityEntityTypes { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
        public virtual ICollection<UserGroup> UserGroups { get; set; }
        public virtual ICollection<UsersRole> UsersRoles { get; set; }
    }
}
