//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TempEfHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CenterType
    {
        public int CenterTypeID { get; set; }
        public string CenterTypeName { get; set; }
        public string coded { get; set; }
        public string terminologyid { get; set; }
    }
}
