//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TempEfHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AreaLocation
    {
        public Tbl_AreaLocation()
        {
            this.TblTravels = new HashSet<TblTravel>();
            this.ProTravels = new HashSet<ProTravel>();
            this.TblTherosholds = new HashSet<TblTheroshold>();
        }
    
        public int AreLocationID { get; set; }
        public string CodeString { get; set; }
        public string areaName { get; set; }
        public string CodeStringParent { get; set; }
        public Nullable<int> areaType { get; set; }
        public string terminology { get; set; }
        public Nullable<int> areaParentId { get; set; }
        public Nullable<System.Guid> UniversityId { get; set; }
        public string EnglishName { get; set; }
    
        public virtual AreaType AreaType1 { get; set; }
        public virtual ICollection<TblTravel> TblTravels { get; set; }
        public virtual ICollection<ProTravel> ProTravels { get; set; }
        public virtual Tbl_University Tbl_University { get; set; }
        public virtual ICollection<TblTheroshold> TblTherosholds { get; set; }
    }
}
