//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TempEfHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Coded
    {
        public Tbl_Coded()
        {
            this.RequestLabs = new HashSet<RequestLab>();
            this.ProClinicalFindings = new HashSet<ProClinicalFinding>();
            this.ProDiagnosis = new HashSet<ProDiagnosi>();
            this.ProDrugHistories = new HashSet<ProDrugHistory>();
            this.ProPastMedicalHistories = new HashSet<ProPastMedicalHistory>();
            this.TblAdverseReactions = new HashSet<TblAdverseReaction>();
            this.TblAdverseReactions1 = new HashSet<TblAdverseReaction>();
            this.TblComplications = new HashSet<TblComplication>();
            this.TblDiagnosis = new HashSet<TblDiagnosi>();
            this.TblDrugHistories = new HashSet<TblDrugHistory>();
            this.TblDrugTreatments = new HashSet<TblDrugTreatment>();
            this.TblPastMedicalHistories = new HashSet<TblPastMedicalHistory>();
        }
    
        public int CodeID { get; set; }
        public string coded { get; set; }
        public string terminologyid { get; set; }
        public string valuee { get; set; }
        public string CodeType { get; set; }
        public string english { get; set; }
        public string EnglishTerm { get; set; }
        public string InterfaceTerm { get; set; }
    
        public virtual ICollection<RequestLab> RequestLabs { get; set; }
        public virtual ICollection<ProClinicalFinding> ProClinicalFindings { get; set; }
        public virtual ICollection<ProDiagnosi> ProDiagnosis { get; set; }
        public virtual ICollection<ProDrugHistory> ProDrugHistories { get; set; }
        public virtual ICollection<ProPastMedicalHistory> ProPastMedicalHistories { get; set; }
        public virtual ICollection<TblAdverseReaction> TblAdverseReactions { get; set; }
        public virtual ICollection<TblAdverseReaction> TblAdverseReactions1 { get; set; }
        public virtual ICollection<TblComplication> TblComplications { get; set; }
        public virtual ICollection<TblDiagnosi> TblDiagnosis { get; set; }
        public virtual ICollection<TblDrugHistory> TblDrugHistories { get; set; }
        public virtual ICollection<TblDrugTreatment> TblDrugTreatments { get; set; }
        public virtual ICollection<TblPastMedicalHistory> TblPastMedicalHistories { get; set; }
    }
}
