//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TempEfHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAdmission
    {
        public TblAdmission()
        {
            this.TblAdverseReactions = new HashSet<TblAdverseReaction>();
            this.TblClinicalFindings = new HashSet<TblClinicalFinding>();
            this.TblComplications = new HashSet<TblComplication>();
            this.TblDeaths = new HashSet<TblDeath>();
            this.TblDiagnosis = new HashSet<TblDiagnosi>();
            this.TblDrugTreatments = new HashSet<TblDrugTreatment>();
            this.TblMSG_Admission = new HashSet<TblMSG_Admission>();
            this.TblPastMedicalHistories = new HashSet<TblPastMedicalHistory>();
            this.TblTravels = new HashSet<TblTravel>();
        }
    
        public long AdmissionID { get; set; }
        public string AdmissionDate { get; set; }
        public Nullable<System.DateTime> AdmissionTime { get; set; }
        public Nullable<int> AdmissionType { get; set; }
        public Nullable<int> InstituteID { get; set; }
        public string MedicalRecordNumber { get; set; }
        public Nullable<int> ReasonforEncounter { get; set; }
        public Nullable<long> PatientID { get; set; }
        public string PaperCode { get; set; }
        public string PostDate { get; set; }
        public string SamplingDate { get; set; }
        public string CompositionUID { get; set; }
    
        public virtual AdmissionType AdmissionType1 { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual ICollection<TblAdverseReaction> TblAdverseReactions { get; set; }
        public virtual ICollection<TblClinicalFinding> TblClinicalFindings { get; set; }
        public virtual ICollection<TblComplication> TblComplications { get; set; }
        public virtual ICollection<TblDeath> TblDeaths { get; set; }
        public virtual ICollection<TblDiagnosi> TblDiagnosis { get; set; }
        public virtual ICollection<TblDrugTreatment> TblDrugTreatments { get; set; }
        public virtual ICollection<TblMSG_Admission> TblMSG_Admission { get; set; }
        public virtual ICollection<TblPastMedicalHistory> TblPastMedicalHistories { get; set; }
        public virtual ICollection<TblTravel> TblTravels { get; set; }
    }
}
