//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TempEfHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMSG_Admission
    {
        public long ID { get; set; }
        public long AdmissionID { get; set; }
        public long MsgID { get; set; }
    
        public virtual TblAdmission TblAdmission { get; set; }
        public virtual TblMSG TblMSG { get; set; }
    }
}
