//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TempEfHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTheroshold
    {
        public int TherosholdID { get; set; }
        public Nullable<int> MethodID { get; set; }
        public Nullable<int> FixNumber { get; set; }
        public Nullable<int> SyndromicId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<byte> PreProcessMethod { get; set; }
        public Nullable<double> Factor { get; set; }
    
        public virtual Tbl_AreaLocation Tbl_AreaLocation { get; set; }
        public virtual Tbl_Syndromic Tbl_Syndromic { get; set; }
    }
}
