//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.TempEfHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTravel
    {
        public long TravelID { get; set; }
        public long AdmissionID { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> AreaLocationID { get; set; }
        public bool BirdHistory { get; set; }
    
        public virtual Tbl_AreaLocation Tbl_AreaLocation { get; set; }
        public virtual Tbl_Country Tbl_Country { get; set; }
        public virtual TblAdmission TblAdmission { get; set; }
    }
}
